### ISSUE TITLE
Import a Mars quadrangles boundaries data set

### ISSUE THREAD

**Issue by nmanaud** [openplanetary/opm#4]

**Comment by thareUSGS** [comment]
I assume you want the 5M quads. There are 2M and 500K quads also. I think you want file Mars_MC_5M_2M_Quads.zip
under ftp://pdsimage2.wr.usgs.gov/pub/pigpen/mars/MCQuad_boundaries/

**Comment by nmanaud** [comment]
Thanks. I've been trying to import these into CARTO, but some unknown reasons (error 9999) it won't let me. I'll keep trying...

**Comment by thareUSGS** [comment]
I notice the 5M quads had a projection set to Earth. I changed to Mars in the download, but I doubt that would matter since it is still just degrees. Otherwise I don't see anything odd in the file. It might be worth a re-download.

**Comment by nmanaud** [comment]
This error was caused because by the field "xmin" name of the shapefile. I changed the field names xmin, xmax, ymin, ymax to xmin1, xmax1, ymin1, ymax1.  Those words are reserved keywords of CARTO, and that's why it was returning an error.

Dataset:
https://openplanetary.carto.com/u/nmanaud/dataset/opm_mars_mc5m_quadsdd_dense

Map:
https://openplanetary.carto.com/u/nmanaud/builder/b893ee98-8345-40d1-a765-5b2a53147f8d/embed
