### ISSUE TITLE
Hillshading is not visible

### ISSUE THREAD

**Issue by nmanaud** [openplanetary/opm#5]
CARTO doesn't seem to handle blending (and opacity lower than 1) of color-coded topography with basemap (Hillshade map). We need to find a work around. Vector hillshade is being explored

**Comment by nmanaud** [comment]
https://carto.com/docs/carto-engine/cartocss/composite-operations/ says:
"Composite operations are blending modes for your map layers. They fall into two main categories: color and alpha, and can be applied to all non-basemap elements in your CARTO map by adding the comp-op value to your CartoCSS code."

**Comment by nmanaud** [comment]
Example:
<img width="1352" alt="mars_basemap_v0_1___carto" src="https://user-images.githubusercontent.com/1929139/30652992-26615b48-9e2a-11e7-90ec-eb7644bfd52d.png">

**Comment by nmanaud** [comment]
Example of what we're expecting: http://openplanetarymap.org/sandbox/maps/map-01.html

**Comment by makella** [comment]
@nmanaud yes, compositing doesn't work with a background basemap layer but what you can do is color your countour layer and use `opacity: 0.5;` (or an appropriate value) using opacity versus polygon-opacity will give you the result (I am pretty sure) for example, that's what I did in this map:
https://team.carto.com/u/mamataakella/builder/bc190683-5a9e-47c3-9975-d66c53e0ab6d/embed

Let me know if that works for you.

**Comment by nmanaud** [comment]
Thanks @makella ! 👍

**Comment by makella** [comment]
great!
