### ISSUE TITLE
Nomenclature polygon data source

### ISSUE THREAD

**Issue by jovrtn** [openplanetary/opm#7]
Curious where the data in the opm_mars_nomenclature_polygons table are from? I haven't been able to find nomenclature data files that aren't just latlng points on the USGS Astrogeology site anywhere.

Thanks!

**Comment by thareUSGS** [comment]
We have been promising approximate boundaries for a while. Thus far we have released some (e.g. to OPM) for testing (just email me). But we are actually testing the updated daily export workflow this week looking for odd wraps and updating the metadata (specifically speaking that they are truly approximate and not appropriate for science). Anyway, look for these boundary releases in the next week or two from the nomenclature download site https://planetarynames.wr.usgs.gov/GIS_Downloads .

**Comment by jovrtn** [comment]
@thareUSGS Awesome, I'll keep an eye out. Much appreciated!
